// Package colab generates Jupyter notebooks that download torrents to Google Drive via Colab.
package colab

import (
	"encoding/base64"
	"encoding/json"
	"strings"
)

// Notebook returns the bytes of a .ipynb file ready to open in Google Colab.
//
// Pass a magnetURI for magnet links, or torrentBytes (raw .torrent content) for files.
// driveFolder is the subfolder within Google Drive root (default: "TorrentDownloads").
func Notebook(displayName, magnetURI string, torrentBytes []byte, driveFolder string) ([]byte, error) {
	if driveFolder == "" {
		driveFolder = "TorrentDownloads"
	}
	outDir := "/content/gdrive/MyDrive/" + driveFolder

	var cells []any

	cells = append(cells, mdCell(
		"# Torrent Download — Google Colab\n",
		"\n",
		"Generated by **Hyperfast Torrent Client** for `"+escMD(displayName)+"`.\n",
		"Run each cell in order. Files will be saved to `My Drive/"+driveFolder+"`.\n",
	))

	// 1. Mount Drive
	cells = append(cells, codeCell(
		"from google.colab import drive\n",
		"drive.mount('/content/gdrive')\n",
		"print('Drive mounted.')\n",
	))

	// 2. Create output directory
	cells = append(cells, codeCell(
		"import os\n",
		"output_dir = "+pyStr(outDir)+"\n",
		"os.makedirs(output_dir, exist_ok=True)\n",
		"print(f'Output directory: {output_dir}')\n",
	))

	// 3. Install aria2c
	cells = append(cells, codeCell(
		"!apt-get install -y aria2 -q\n",
		"print('aria2c ready.')\n",
	))

	// 4a. For .torrent files: base64-decode and write to disk
	if len(torrentBytes) > 0 {
		b64 := base64.StdEncoding.EncodeToString(torrentBytes)
		cells = append(cells, codeCell(
			"import base64\n",
			"_torrent_b64 = "+pyStr(b64)+"\n",
			"torrent_path = '/tmp/download.torrent'\n",
			"with open(torrent_path, 'wb') as _f:\n",
			"    _f.write(base64.b64decode(_torrent_b64))\n",
			"print(f'Torrent written: {torrent_path}')\n",
		))
	}

	// 4b. Download
	var srcLine string
	if len(torrentBytes) > 0 {
		srcLine = "source = torrent_path\n"
	} else {
		srcLine = "source = " + pyStr(magnetURI) + "\n"
	}
	cells = append(cells, codeCell(
		"# Downloading: "+escPyComment(displayName)+"\n",
		srcLine,
		"import subprocess\n",
		"cmd = [\n",
		"    'aria2c',\n",
		"    '--enable-dht=true',\n",
		"    '--seed-time=0',\n",
		"    '--max-connection-per-server=16',\n",
		"    '--split=16',\n",
		"    '--min-split-size=1M',\n",
		"    '--file-allocation=none',\n",
		"    '--bt-enable-lpd=false',\n",
		"    '--console-log-level=notice',\n",
		"    f'--dir={output_dir}',\n",
		"    source,\n",
		"]\n",
		"result = subprocess.run(cmd)\n",
		"print(f'aria2c exit code: {result.returncode}')\n",
	))

	// 5. List downloaded files
	cells = append(cells, codeCell(
		"print('\\n=== Downloaded Files ===')\n",
		"for root, _, files in os.walk(output_dir):\n",
		"    for name in files:\n",
		"        path = os.path.join(root, name)\n",
		"        mb = os.path.getsize(path) / 1024 / 1024\n",
		"        print(f'  {path}  ({mb:.1f} MB)')\n",
		"print('=========================')\n",
	))

	// 6. Instructions
	cells = append(cells, mdCell(
		"## Getting Your Files\n",
		"\n",
		"Files are now in **Google Drive → My Drive → "+driveFolder+"**.\n",
		"\n",
		"**Option A — Download directly from Drive:**  \n",
		"Open [drive.google.com](https://drive.google.com), navigate to `"+driveFolder+"`,  \n",
		"right-click the file → **Download**.\n",
		"\n",
		"**Option B — Use Hyperfast Torrent Client:**  \n",
		"In the app, open the **From Drive** tab, paste the Google Drive share link,  \n",
		"pick a local folder, and click **Download Locally**.\n",
	))

	nb := map[string]any{
		"nbformat":       4,
		"nbformat_minor": 5,
		"metadata": map[string]any{
			"colab": map[string]any{
				"name": "torrent-" + safeName(displayName) + ".ipynb",
			},
			"kernelspec": map[string]any{
				"display_name": "Python 3",
				"name":         "python3",
			},
			"language_info": map[string]any{
				"name": "python",
			},
		},
		"cells": cells,
	}
	return json.MarshalIndent(nb, "", "  ")
}

func codeCell(lines ...string) map[string]any {
	return map[string]any{
		"cell_type":       "code",
		"metadata":        map[string]any{},
		"source":          lines,
		"execution_count": nil,
		"outputs":         []any{},
	}
}

func mdCell(lines ...string) map[string]any {
	return map[string]any{
		"cell_type": "markdown",
		"metadata":  map[string]any{},
		"source":    lines,
	}
}

// pyStr wraps s in Python double-quote string literal, escaping as needed.
func pyStr(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	s = strings.ReplaceAll(s, "\n", `\n`)
	s = strings.ReplaceAll(s, "\r", `\r`)
	return `"` + s + `"`
}

func safeName(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteByte('-')
		}
	}
	out := b.String()
	if len(out) > 40 {
		return out[:40]
	}
	return out
}

func escMD(s string) string {
	s = strings.ReplaceAll(s, "`", "\\`")
	s = strings.ReplaceAll(s, "*", "\\*")
	return s
}

func escPyComment(s string) string {
	return strings.ReplaceAll(s, "\n", " ")
}
